- name: Create a GCP instance
  hosts: localhost
  vars:
     gcp_project: ansible-demo-ict
     gcp_cred_kind: serviceaccount
  tasks:
    - name: create a disk mapped from Ubuntu 18.04 image
      gcp_compute_disk:
        name: disk-instance
        size_gb: 10
        source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts'
        zone: asia-southeast2-a	
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: present
      register: disk

    - name: create the Ubuntu 18.04 instance
      gcp_compute_instance:
        name: wordpress-ubuntu
        machine_type: n1-standard-1
        disks:
        - auto_delete: 'true'
          boot: 'true'
          source: "{{ disk }}"
        zone: asia-southeast2-a
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: present
    - name: Show Ubuntu 18.04 Instance Details
      debug:
        msg: "The wordpress-ubuntu instance is accessible at {{ address.address }}"
