- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars:
      gcp_project: ansible-demo-ict
      gcp_cred_kind: serviceaccount
      zone: "asia-southeast2-a"
      region: "asia-southeast2"

  tasks:
   - name: create a disk
     gcp_compute_disk:
         name: 'disk-instance'
         size_gb: 10
         source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         state: present
     register: disk
   - name: create a address
     gcp_compute_address:
         name: 'address-instance'
         region: "{{ region }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         state: present
     register: address
   - name: create a instance
     gcp_compute_instance:
         state: present
         name: ubuntu-wordpress
         machine_type: n1-standard-1
         disks:
           - auto_delete: true
             boot: true
             source: "{{ disk }}"
         network_interfaces:
             - network: null # use default
               access_configs:
                 - name: 'External NAT'
                   nat_ip: "{{ address }}"
                   type: 'ONE_TO_ONE_NAT'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
     register: instance

   - name: Wait for SSH to come up
     wait_for: host={{ address.address }} port=22 delay=10 timeout=60
   
   - name: Create Firewall HTTP Allow
     community.general.gce_net:
       name: default
       fwname: "Allow HTTP"
       allowed: tcp:80
       state: "present"
       src_range: ['0.0.0.0/0']
