- name: Housekeeping GCP instance
  hosts: localhost
  vars:
     gcp_project: enhanced-cable-281809
     gcp_cred_kind: serviceaccount
  tasks:
    - name: delete an instance
      gcp_compute_instance:
        name: ubuntu-wordpress
        zone: asia-southeast2-a
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: absent
